#!/bin/sh

retry=1
max_retry=3

while true
do
    DEBIAN_FRONTEND=noninteractive apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q "$@"
    return_value=$?
    [ $return_value -eq 0 ] && break
    [ $retry -eq $max_retry ] && exit $return_value

    echo "================================================="
    echo "($retry) Install failed... Retrying after some seconds"
    echo "================================================="

    sleep 20
    retry=$((retry+1))
done
