#!/bin/sh

if gpg --keyserver pgp.mit.edu --recv-keys "$@" >/dev/null; then
    gpg --armor --export "$@" | sudo apt-key add -
else
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q "$@"
fi

exit 0
