#!/bin/sh

#set proxy in /etc/opkg/opkg.conf if required
unset http_proxy

retry=1
max_retry=3

which opkg
rc=$?

if [ $rc -ne 0 ]; then
    echo "Error: OPKG package manager not found in the path."
    exit $rc
fi

while true
do
    opkg update
    opkg install "$@"
    return_value=$?
    [ $return_value -eq 0 ] && break
    [ $retry -eq $max_retry ] && exit $return_value

    echo "================================================="
    echo "($retry) Install failed... Retrying after some seconds"
    echo "================================================="

    sleep 20
    retry=$((retry+1))
done
