#!/bin/bash

retry=1
max_retry=3

while true
do
    zypper -n update
    zypper -q install -f "$@"
    return_vale=$?
    [ $return_value -eq 0 ] && break
    [ $retry -eq $max_retry ] && exit $return_value

    echo "================================================="
    echo "($retry) Install failed... Retrying after some seconds"
    echo "================================================="

    sleep 20
    retry=$((retry+1))
done
