#!/bin/bash

retry=0
max_retry=3

while [ 1 ] 
do
    zypper -n update 
    zypper -q install -f "$@"
    return_vale=$?
    [ "$return_value" -eq 0 ] && break
    [ "$retry" -eq "$max_retry" ] && exit $return_value

    echo "================================================="
    echo "$retry  Install failed... Retrying after some seconds"
    echo "================================================="

    sleep 60
    retry=$((retry+1))
done
